### ISSUE TITLE
Publish Helm-Chart

### ISSUE THREAD

**Issue by grafjo** [getlago/lago-helm-charts#14]
please publish this helm chart, so others can use it easily via helm.

there is a gh action that supports publishing helm charts via gh pages.

https://helm.sh/docs/howto/chart_releaser_action/

**Comment by electrosenpai** [comment]
Hello @grafjo, sorry for the late notice. I just arrived inside Lago and I will take care of this next week :)

**Comment by electrosenpai** [comment]
This is now live, see #67
