### ISSUE TITLE
Postgresql bad URI

### ISSUE THREAD

**Issue by drew-viles** [getlago/lago-helm-charts#33]
When trying to run the helm chart with my own Postgresql instance, I'm getting the following

```
URI::InvalidURIError: bad URI(is not URI?): postgresql://lago:MY_SECURE_PASSWORD@postgresql-pgpool.sql-postgres.svc:5432/lago (URI::InvalidURIError)
```

I've removed special characters from my password and it works fine. This suggests some escaping might be happening in an ENV var (at a guess).

The password it shows in the error macthes what I have so it's correct in the URI.

Looking further into it, it seems similar to the last comment in this thread.
https://stackoverflow.com/questions/28976639/undefined-method-default-timezone-for-activerecordbaseclass-on-ubuntu-14

I suspect this issue probably needs moving upstream into one of the other lago repos but this is where I hit it so thought I'd raise it here,.

**Comment by jdenquin** [comment]
@drew-viles did you tried to URL encode the password?

**Comment by drew-viles** [comment]
aaah I did not. I didn't realise I needed to do it on my end. I just presumed it was something the app would do - fwiw, I'm an absolute Ruby noob as I live in Golang 😆

So my secret gets pulled from vault using the External Secrets Operator and a secret generated from that.
I'll look into what I can do on my side to see if I can resolve it once I've finished playing with the helm charts in my PR

**Comment by jdenquin** [comment]
the database URL should be URI parsed, but I've never had an issue like this one with specific characters, if you can double check it, would be awesome!

**Comment by drew-viles** [comment]
ok so I've done a bit of testing and here are my findings:

I've been using the helm command ` helm upgrade --install lago-test . --set apiUrl=http://localhost:3000 --set frontUrl=http://localhost:8080 --set global.databaseUrl="<URI>" --set postgresql.enabled=false` to run all tests and adjusted the password as shown below.

1. `postgresql://lago:Abc£$%^&*123@127.0.0.1:5432/lago` - failed
2. `postgresql://lago:Abc£%^&*123@127.0.0.1:5432/lago` - failed
3. `postgresql://lago:Abc£$^&*123@127.0.0.1:5432/lago` - failed
4. `postgresql://lago:Abc£$%&*123@127.0.0.1:5432/lago` - failed
5. `postgresql://lago:Abc£$%^*123@127.0.0.1:5432/lago` - failed
6. `postgresql://lago:Abc£$%^&123@127.0.0.1:5432/lago` - failed

So all of these symbols appear to be failing.

I then ran with  `postgresql://lago:Abc%C2%A3%24%25%5E%26123@127.0.0.1:5432/lago` and I no longer got the error. I actually have a DB to connect to so the connection was refused however, this is getting passed the URI Encoding error.

**Comment by jdenquin** [comment]
okay so we have to encode this URI and the password, did you managed to get your database working?

**Comment by drew-viles** [comment]
I did but without the pre-encoded characters in the uri or by removing the non-alphanum characters.

**Comment by jdenquin** [comment]
any news around it @drew-viles

**Comment by drew-viles** [comment]
Not from my side I'm afraid. Unfortunately I've not touched this much over the past couple months as the company went ina. different direction unfortunately. However for the record as it may help diagnose things, I couldn't get this working unless I changed the password and removed "special characters" **or** URL encoded things prior to lago recieving the secret. So for example, I url encoded the secret in vault, external secrets syncs the secret to the cluster and then Lago took that secret pre-encoded.

**Comment by jdenquin** [comment]
Ok, I close this issue since it should be on encoding side!
