### ISSUE TITLE
Chart updates not being published to charts.getlago.com

### ISSUE THREAD

**Issue by chriswessels** [getlago/lago-helm-charts#54]
The latest version of the chart available via https://charts.getlago.com/ is 1.0.0, yet 1.4.0 has been committed most recently.

**Comment by jdenquin** [comment]
hello @chriswessels, yes sorry for it it's still manual, I'll update it!

**Comment by gilliangoud** [comment]
@jdenquin Would you like a workflow that creates the artifact automatically for you?

**Comment by jdenquin** [comment]
would be awesome, feel free to open a PR @gilliangoud

**Comment by gilliangoud** [comment]
Created pr #55

**Comment by jdenquin** [comment]
this is now handled and we updated our URL to https://helm.getlago.com
