### ISSUE TITLE
Error while deploying on EKS

### ISSUE THREAD

**Issue by akashg116414** [getlago/lago-helm-charts#57]
Hello, Can someone help here,

**Error:**

│   Normal   Scheduled           2m43s  default-scheduler        Successfully assigned lago/lago-worker-59d56d585c-rmg85 to ip-10-46-13-162.ap-southeast-1.compute.internal                                                                 ││   Warning  FailedAttachVolume  2m43s  attachdetach-controller  Multi-Attach error for volume "pvc-21a75921-9e01-4324-9072-5c0c529557bc" Volume is already used by pod(s) lago-api-79d77799-jmdn9

**Comment by jdenquin** [comment]
Hello @akashg116414 

You should use S3 since PVC and RWM is not easy with EKS

**Comment by electrosenpai** [comment]
> Hello, Can someone help here,
> 
> **Error:**
> 
> │ Normal Scheduled 2m43s default-scheduler Successfully assigned lago/lago-worker-59d56d585c-rmg85 to ip-10-46-13-162.ap-southeast-1.compute.internal ││ Warning FailedAttachVolume 2m43s attachdetach-controller Multi-Attach error for volume "pvc-21a75921-9e01-4324-9072-5c0c529557bc" Volume is already used by pod(s) lago-api-79d77799-jmdn9

Hello,

To resolve the issue you're encountering with the PVC being attached to multiple pods, I would suggest considering one of the following options:

1. **Use S3 storage**: This is the recommended option. By leveraging S3, you can avoid the complications that come with managing Persistent Volume Claims (PVCs), as data is stored externally and can be accessed by multiple pods without any limitations.

2. **Use MinIO**: If you're working in a local environment or prefer to keep everything within your own cluster, MinIO is a viable alternative, as it provides S3-compatible storage. However, please note that we do not recommend this option for production environments.

In general, avoiding the use of PVC for workloads that require access from multiple pods is advisable.
