### ISSUE TITLE
PDF deployment does not support ARM

### ISSUE THREAD

**Issue by severos** [getlago/lago-helm-charts#78]
Current PDF deployment is version 7.8.2 which is AMD only
https://github.com/getlago/lago-helm-charts/blob/5af7bbda386e59d8624af86d8f37a454ae0ccc3d/templates/pdf-deployment.yaml#L25

Could we update to least 7.10 to support ARM?

**Comment by severos** [comment]
PR: https://github.com/getlago/lago-helm-charts/pull/81

**Comment by jdenquin** [comment]
Fixed by using 7.10, thanks for it!
