### ISSUE TITLE
PDF deployment replica does not honor values

### ISSUE THREAD

**Issue by severos** [getlago/lago-helm-charts#79]
PDF deployment uses a constant replica count of 1
https://github.com/getlago/lago-helm-charts/blob/5af7bbda386e59d8624af86d8f37a454ae0ccc3d/templates/pdf-deployment.yaml#L8
And does not honor the helm values:
https://github.com/getlago/lago-helm-charts/blob/5af7bbda386e59d8624af86d8f37a454ae0ccc3d/values.yaml#L179

**Comment by severos** [comment]
PR: https://github.com/getlago/lago-helm-charts/pull/80

**Comment by jdenquin** [comment]
Merged, thanks for fixing it!
