### ISSUE TITLE
Chart Repository doesn't contain latest version

### ISSUE THREAD

**Issue by FinweVI** [getlago/lago-helm-charts#82]
Hello,

I'm trying to deploy Lago through Helm/Terraform.
The repository doesn't seem to be documented, but I found it through the GitHub Workflow: https://charts.getlago.com/

However, it doesn't contains the latest version of the chart, only the 1.0.

**Comment by electrosenpai** [comment]
I manually update so it should be good.

`NAME           	CHART VERSION	APP VERSION                 	DESCRIPTION
lago/lago      	1.12.3       	1.12.3                      	the Lago open source billing app
lago/minio     	5.2.0        	RELEASE.2024-04-18T19-09-19Z	High Performance Object Storage
lago/postgresql	13.2.2       	16.0.0                      	PostgreSQL (Postgres) is an open source object-...
lago/redis     	18.2.1       	7.2.3                       	Redis(R) is an open source, advanced key-value ...`

I will also make a new release today to be sure the workflow is working correctly
