### ISSUE TITLE
Minio not bundled with the archives

### ISSUE THREAD

**Issue by FinweVI** [getlago/lago-helm-charts#83]
Hello,

it seems like the Minio chart is not bundled (unlike PostGreSQL/Redis) in the released archives, which throws errors when deploying (even if I use AWS).

**Comment by electrosenpai** [comment]
> Hello,
> 
> it seems like the Minio chart is not bundled (unlike PostGreSQL/Redis) in the released archives, which throws errors when deploying (even if I use AWS).

Hi @FinweVI ,

Thank you for bringing this up! To better assist you and help resolve the issue, could you please share the exact commands and steps you followed during the deployment? This will help me replicate the process on my end, allowing me to debug and reproduce the situation more accurately.

**Comment by FinweVI** [comment]
Hello,

just downloading the latest (at the time) release and inspecting the archive in the `charts` folder: https://github.com/getlago/lago-helm-charts/archive/refs/tags/1.12.3.zip

It seems to have been fixed on 1.15 though, thanks.
