### ISSUE TITLE
Worker doesn't start when minio enabled

### ISSUE THREAD

**Issue by muratdacic** [getlago/lago-helm-charts#87]
When minio enabled, worker is searching for non existing pvc, because there is a missing condition.
Line 179 and 185 in worker-deployment.yaml, instead of           

{{ if not .Values.global.s3.enabled }}

can someone just put 

 {{- if and (not .Values.global.s3.enabled) (not .Values.minio.enabled) }}

**Comment by grthr** [comment]
Same issue here: The PVC is still referenced in the lago-worker.

And there is no s3/minio configuration in lago-worker when minio is enabled.

**Comment by electrosenpai** [comment]
> {{ if not .Values.global.s3.enabled }}

Good catch here sorry about that. PR is on the way

**Comment by grthr** [comment]
what about S3 credentials in lago-worker if using minio? I would expect S3 environment variables in the worker-deployment just like in api-deployment: https://github.com/getlago/lago-helm-charts/blob/7d1856e362f48a0e26d868d11637469b059e7e85/templates/api-deployment.yaml#L148

**Comment by electrosenpai** [comment]
Correct @grthr [PR](https://github.com/getlago/lago-helm-charts/pull/91) is on the way

**Comment by electrosenpai** [comment]
Its now merge & should be good. Feel free to re-open  this issue if its doesn't solve.
